# Audio alignment demo (SGPA)

**This notebook does not build datasets.** It is a visual QA tool for `SpectrogramGuidedAligner` (SGPA; see `mllm_shap/connectors/base/audio.py`) on data already published to [Pawlo77/mllm-shap](https://huggingface.co/datasets/Pawlo77/mllm-shap).

## Purpose

Downstream experiments (SHAP attribution, faithfulness, interspeech) need **token-level audio segments**: each explainability token must map to a time range (and optionally a clipped waveform). SGPA implements that alignment (Wav2Vec2 CTC + spectrogram boundary refinement).

This notebook:

1. Loads a prepared Hub config (e.g. `multi_sentence`, `multi_lingual`) and picks a random row.
2. Tokenizes the first sentence with `bert-base-multilingual-cased` (stand-in for the tokenizer used in analysis).
3. Runs `SpectrogramGuidedAligner` on synthesized audio (`audio__male` by default).
4. Renders an HTML table: token, start/end time, duration, confidence, and an inline audio player per token.

Use it to **listen and inspect** alignments before long GPU runs—not to filter, sample, or upload data.

In [1]:
%load_ext autoreload
%autoreload 2
%config InlineBackend.figure_format = "retina"

import warnings

warnings.filterwarnings("ignore", category=FutureWarning)

In [ ]:
from src.setup import configure_notebook_environment

configure_notebook_environment(set_plot_style=False)

PosixPath('/Users/pawelp/Desktop/education/pw/bachelor/MLLM-Shap')

In [ ]:
from datasets import load_dataset

from src.audio_alignment_demo import (
    create_sgpa_demo,
    display_random_alignment_example,
)

HUB_NAME = "Pawlo77/mllm-shap"
HUB_REVISION = "main"
CONFIG_MULTI_SENTENCE = "multi_sentence__voice_bench"
CONFIG_MULTI_LINGUAL = "multi_lingual__infinity_instruct"
SPLIT = "test"

aligner, tokenizer = create_sgpa_demo()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
I0522 15:42:02.748700 3387537 fork_posix.cc:71] Other threads are currently calling into gRPC, skipping fork() handlers

Loading weights:   0%|          | 0/404 [00:00<?, ?it/s]

In [4]:
aligner, tokenizer = create_sgpa_demo()

Loading weights:   0%|          | 0/404 [00:00<?, ?it/s]

In [5]:
ds = load_dataset(
    HUB_NAME, name=CONFIG_MULTI_SENTENCE, split=SPLIT, revision=HUB_REVISION
).to_pandas()  # nosec B615

display_random_alignment_example(ds, aligner=aligner, tokenizer=tokenizer)

Aligning to transcript: 'What is LILO and GRUB used for in Linux system?'

Aligning to 16 tokens: ['[CLS]', 'What', 'is', 'L', '##IL', '##O', 'and', 'GR', '##UB', 'used', 'for', 'in', 'Linux', 'system', '?', '[SEP]']

In [6]:
display_random_alignment_example(ds, aligner=aligner, tokenizer=tokenizer)

Aligning to transcript: 'Good morning.'

Aligning to 5 tokens: ['[CLS]', 'Good', 'morning', '.', '[SEP]']

In [7]:
display_random_alignment_example(ds, aligner=aligner, tokenizer=tokenizer)

Aligning to transcript: 'Pretend to be a world-famous chef.'

Aligning to 12 tokens: ['[CLS]', 'Pre', '##tend', 'to', 'be', 'a', 'world', '-', 'famous', 'chef', '.', '[SEP]']

In [8]:
ds = load_dataset(
    HUB_NAME, name=CONFIG_MULTI_LINGUAL, split=SPLIT, revision=HUB_REVISION
).to_pandas()  # nosec B615

display_random_alignment_example(ds, aligner=aligner, tokenizer=tokenizer)

Aligning to transcript: 'dis-moi une phrase de Fray Luis de León'

Aligning to 13 tokens: ['[CLS]', 'dis', '-', 'moi', 'une', 'phrase', 'de', 'Fra', '##y', 'Luis', 'de', 'León', '[SEP]']

In [9]:
display_random_alignment_example(ds, aligner=aligner, tokenizer=tokenizer)

Aligning to transcript: 'Por favor comparte una cita de Gracián Baltasar.'

Aligning to 16 tokens: ['[CLS]', 'Por', 'favor', 'com', '##parte', 'una', 'cita', 'de', 'G', '##rac', '##ián', 'Bal', '##tas', '##ar', '.', '[SEP]']

In [10]:
display_random_alignment_example(ds, aligner=aligner, tokenizer=tokenizer)

Aligning to transcript: 'Translate the text into Spanish.'

Aligning to 9 tokens: ['[CLS]', 'Trans', '##late', 'the', 'text', 'into', 'Spanish', '.', '[SEP]']

Conclusion: audio segments are quite well aligned with tokens, however this method should rely on tokenizer that do not include any system tokens and works well with given language. Short tokens seems to be aligned worse than longer ones. Word-level alignment could be a better approach in this case.